# Generated by Django 5.0.7 on 2024-08-03 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_tour_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='id',
            new_name='tour_id',
        ),
    ]
