# Generated by Django 5.0.7 on 2024-08-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_remove_tour_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='tour_id',
        ),
    ]
