# Generated by Django 5.0.7 on 2024-08-04 08:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_data_mig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='tour_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
