# Generated by Django 5.0.7 on 2024-08-04 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='userId',
            new_name='booking_id',
        ),
        migrations.AddField(
            model_name='bookings',
            name='user_id',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
