# Generated by Django 5.0.7 on 2024-08-03 13:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='id',
            field=models.IntegerField()
        ),
    ]
