# Generated by Django 5.0.7 on 2024-08-03 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_rename_id_tour_tour_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='reviews',
        ),
    ]
