# Generated by Django 4.2.4 on 2024-07-25 18:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('userId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('userEmail', models.EmailField(max_length=254)),
                ('tourName', models.CharField(max_length=254)),
                ('fullName', models.CharField(max_length=254)),
                ('guestSize', models.IntegerField()),
                ('phone', models.IntegerField(max_length=10)),
                ('bookAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
